export const listVideo1 = [
    {
        key: 'sT4385',
        name: 'Allswell - Reload with Redbull',
        durations: 15,
        loop: 3,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 'sT4382',
        name: 'Darlie - White Supreme Enzyme',
        durations: 15,
        loop: 4,
        category: 'hello',
        restriction: '',
    },
    {
        key: 'sT4383',
        name: 'Firefly - Book Now',
        durations: 25,
        loop: 3,
        category: 'Travel',
        restriction: '',
    },
    {
        key: 'sT4384',
        name: 'Skechers - Slip Ins',
        durations: 30,
        loop: 4,
        category: 'Product',
        restriction: '',
    },
    {
        key: 'sT4389',
        name: 'Shaw - Retribution',
        durations: 15,
        loop: 4,
        category: 'Movie',
        restriction: '',
    },
    {
        key: 'sT4386',
        name: 'Tour de France - Singapore Criterium23',
        durations: 40,
        loop: 2,
        category: 'Travel',
        restriction: '',
    },
    {
        key: 'sCM012',
        name: 'OOH',
        durations: 10,
        loop: 1,
        category: 'Media',
        restriction: 'No Back to Back With FMSG Contents',
    },
    {
        key: 'sCM008',
        name: 'FMSG Hiring',
        durations: 15,
        loop: 1,
        category: 'Hiring',
        restriction: '',
    },
    {
        key: 'sT4388',
        name: 'Shopee - Nine Nine 2023',
        durations: 15,
        loop: 3,
        category: 'E-commerce',
        restriction: '',
    },
    {
        key: 'sCM012',
        name: 'OOH',
        durations: 10,
        loop: 1,
        category: 'Media',
        restriction: 'No Back to Back With FMSG Contents',
    },
    {
        key: 'sCM008',
        name: 'FMSG Hiring',
        durations: 15,
        loop: 1,
        category: 'Hiring',
        restriction: '',
    },
    {
        key: 'sT4390',
        name: 'Disney - A Haunting in Venice Pre',
        durations: 30,
        loop: 3,
        category: 'movie',
        restriction: '',
    },
];

export const listVideo2 = [
    {
        key: 'CAM220',
        name: 'Nespresso - Momento',
        durations: 15,
        loop: 2,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 'CAM219',
        name: 'Nespresso - Professional',
        durations: 15,
        loop: 2,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 'CAM217',
        name: 'Kaplan UCD - Over Thirty Years ',
        durations: 15,
        loop: 4,
        category: 'Education',
        restriction: '',
    },
    {
        key: 'sT4386',
        name: 'Tour de France - Singapore Criterium23',
        durations: 40,
        loop: 3,
        category: 'Travel',
        restriction: '',
    },
    {
        key: 'CAM222',
        name: 'Crystal Tomato - Branding',
        durations: 15,
        loop: 3,
        category: '',
        restriction: 'No Back to Back With Crystal Tomato',
    },
    {
        key: 'CAM223',
        name: 'Crystal Tomato - Skin Clarity Cream',
        durations: 15,
        loop: 3,
        category: '',
        restriction: 'No Back to Back With Crystal Tomato',
    },
    {
        key: 'CAM225',
        name: 'Dr D Aesthetics - CIMB Prices',
        durations: 30,
        loop: 1,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 'CAM221',
        name: 'CIMB - CASA Aug_230817',
        durations: 15,
        loop: 2,
        category: '',
        restriction: '',
    },
    {
        key: 'sCM012',
        name: 'OOH',
        durations: 10,
        loop: 3,
        category: '',
        restriction: 'No Back to Back With FMSG Contents',
    },
];

export const listVideo3 = [
    {
        key: 'sT4385',
        name: 'Allswell - Reload with Redbull',
        durations: 15,
        loop: 3,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 'sT4382',
        name: 'Darlie - White Supreme Enzyme',
        durations: 15,
        loop: 4,
        category: '',
        restriction: '',
    },
    {
        key: 'sT4383',
        name: 'Firefly - Book Now',
        durations: 25,
        loop: 3,
        category: 'Travel',
        restriction: '',
    },
    {
        key: 'sT4384',
        name: 'Skechers - Slip Ins',
        durations: 30,
        loop: 4,
        category: '',
        restriction: '',
    },
    {
        key: 'sT4389',
        name: 'Shaw - Retribution',
        durations: 15,
        loop: 4,
        category: 'Movie',
        restriction: '',
    },
    {
        key: 'sT4386',
        name: 'Tour de France - Singapore Criterium23',
        durations: 40,
        loop: 2,
        category: '',
        restriction: '',
    },
    {
        key: 'sCM012',
        name: 'OOH',
        durations: 10,
        loop: 1,
        category: '',
        restriction: 'No Back to Back With FMSG Contents',
    },
    {
        key: 'sCM008',
        name: 'FMSG Hiring',
        durations: 15,
        loop: 1,
        category: '',
        restriction: '',
    },
    {
        key: 'sT4388',
        name: 'Shopee - Nine Nine 2023',
        durations: 15,
        loop: 3,
        category: 'E-commerce',
        restriction: '',
    },
    {
        key: 'sT4390',
        name: 'Disney - A Haunting in Venice Pre',
        durations: 30,
        loop: 3,
        category: 'movie',
        restriction: '',
    },
];

export const listVideo4 = [
    {
        key: 'sT4380',
        name: 'WB - Blue Beetle Cinemas Now',
        durations: 30,
        loop: 3,
        category: 'Movie',
        restriction: '',
    },
    {
        key: 'sT4383',
        name: 'Firefly - Book Now',
        durations: 25,
        loop: 3,
        category: 'Travel',
        restriction: '',
    },
    {
        key: 'sT4384',
        name: 'Skechers - Slip Ins',
        durations: 30,
        loop: 4,
        category: 'Product',
        restriction: '',
    },
    {
        key: 'sT4387',
        name: 'Live Nation - SMSP Aug23',
        durations: 15,
        loop: 3,
        category: 'Event/concert',
        restriction: '',
    },
    {
        key: 'sCM008',
        name: 'FMSG Hiring',
        durations: 15,
        loop: 1,
        category: 'Hiring',
        restriction: '',
    },
    {
        key: 'sT4386',
        name: 'Tour de France - Singapore Criterium23',
        durations: 40,
        loop: 2,
        category: 'Travel',
        restriction: '',
    },
    {
        key: 'sCM012',
        name: 'OOH',
        durations: 10,
        loop: 1,
        category: 'Media',
        restriction: 'No Back to Back With FMSG Contents',
    },
];
