export const listVideo1 = [
    {
        key: 1,
        name: 'Allswell - Red Bull',
        durations: 15,
        loop: 3,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 2,
        name: 'Darlie',
        durations: 15,
        loop: 4,
        category: '',
        restriction: '',
    },
    {
        key: 3,
        name: 'Firefly',
        durations: 25,
        loop: 3,
        category: 'Travel',
        restriction: '',
    },
    {
        key: 4,
        name: 'Skechers',
        durations: 30,
        loop: 4,
        category: '',
        restriction: '',
    },
    {
        key: 5,
        name: 'Shaw - Retribution',
        durations: 15,
        loop: 4,
        category: 'Movie',
        restriction: '',
    },
    {
        key: 6,
        name: 'Tour de France',
        durations: 40,
        loop: 2,
        category: '',
        restriction: '',
    },
    {
        key: 7,
        name: 'Captive Media OOH Video 2',
        durations: 10,
        loop: 1,
        category: '',
        restriction: 'No Back to Back With FMSG Contents',
    },
    {
        key: 8,
        name: 'FMSG Hiring',
        durations: 15,
        loop: 1,
        category: '',
        restriction: '',
    },
];

export const listVideo2 = [
    {
        key: 1,
        name: 'Nespresso',
        durations: 15,
        loop: 2,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 2,
        name: 'Nespresso',
        durations: 15,
        loop: 2,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 3,
        name: 'Kaplan UCD',
        durations: 15,
        loop: 4,
        category: 'Education',
        restriction: '',
    },
    {
        key: 4,
        name: 'Tour de France',
        durations: 40,
        loop: 3,
        category: '',
        restriction: '',
    },
    {
        key: 5,
        name: 'Crystal Tomato',
        durations: 15,
        loop: 3,
        category: '',
        restriction: 'No Back to Back With Crystal Tomato',
    },
    {
        key: 6,
        name: 'Crystal Tomato',
        durations: 15,
        loop: 3,
        category: '',
        restriction: 'No Back to Back With Crystal Tomato',
    },
    {
        key: 7,
        name: 'CIMB',
        durations: 30,
        loop: 1,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 8,
        name: 'CIMB',
        durations: 15,
        loop: 2,
        category: '',
        restriction: '',
    },
    {
        key: 9,
        name: 'Captive Media OOH Video 2',
        durations: 10,
        loop: 3,
        category: '',
        restriction: 'No Back to Back With FMSG Contents',
    },
];

export const listVideo3 = [
    {
        key: 1,
        name: 'Allswell - Red Bull',
        durations: 15,
        loop: 3,
        category: 'F&B',
        restriction: '',
    },
    {
        key: 2,
        name: 'Darlie',
        durations: 15,
        loop: 4,
        category: '',
        restriction: '',
    },
    {
        key: 3,
        name: 'Firefly',
        durations: 25,
        loop: 3,
        category: 'Travel',
        restriction: '',
    },
    {
        key: 4,
        name: 'Skechers',
        durations: 30,
        loop: 4,
        category: '',
        restriction: '',
    },
    {
        key: 5,
        name: 'Shaw - Retribution',
        durations: 15,
        loop: 4,
        category: 'Movie',
        restriction: '',
    },
    {
        key: 6,
        name: 'Tour de France',
        durations: 40,
        loop: 2,
        category: '',
        restriction: '',
    },
    {
        key: 7,
        name: 'Captive Media OOH Video 2',
        durations: 10,
        loop: 1,
        category: '',
        restriction: 'No Back to Back With FMSG Contents',
    },
    {
        key: 8,
        name: 'FMSG Hiring',
        durations: 15,
        loop: 1,
        category: '',
        restriction: '',
    },
    {
        key: 9,
        name: 'Sun Plaza',
        durations: 150,
        loop: 1,
        category: '',
        restriction: 'No Back to Back With F&B',
    },
];
